[project]
name = "nba-fancolor-30"
version = "0.1.0"
description = "NBA team favor grid generator"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow==12.0.0",
    "streamlit==1.51.0",
    "streamlit-drawable-canvas-fix==0.9.8",
]
